# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformProviderDocsLocal < Formula
  desc "A tool for managing and browsing local copies of Terraform provider documentation"
  homepage "https://github.com/jreslock/terraform-provider-docs-local"
  version "0.0.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jreslock/terraform-provider-docs-local/releases/download/v0.0.16/terraform-provider-docs-local_Darwin_x86_64.tar.gz"
      sha256 "d5de4b76d35a1f1b2697c2b8f469ad27d9c8949590417f97d6cb5760728797aa"

      def install
        bin.install "terraform-provider-docs-local-darwin-#{Hardware::CPU.arch}" => "terraform-provider-docs-local"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jreslock/terraform-provider-docs-local/releases/download/v0.0.16/terraform-provider-docs-local_Darwin_arm64.tar.gz"
      sha256 "fb7458c8c61782e3539377d58bdc08a021e4c1eda5adeb92388a6ccf948913fb"

      def install
        bin.install "terraform-provider-docs-local-darwin-#{Hardware::CPU.arch}" => "terraform-provider-docs-local"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jreslock/terraform-provider-docs-local/releases/download/v0.0.16/terraform-provider-docs-local_Linux_x86_64.tar.gz"
        sha256 "3e56e852a930e95baff66d329666a76ddcaf68523c9a90980c636339558b5790"

        def install
          bin.install "terraform-provider-docs-local-darwin-#{Hardware::CPU.arch}" => "terraform-provider-docs-local"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jreslock/terraform-provider-docs-local/releases/download/v0.0.16/terraform-provider-docs-local_Linux_arm64.tar.gz"
        sha256 "5bee9ae4777ae17a42289e82bff6b45f052021f5c3fd2e5560bc093e62988a1b"

        def install
          bin.install "terraform-provider-docs-local-darwin-#{Hardware::CPU.arch}" => "terraform-provider-docs-local"
        end
      end
    end
  end

  test do
    system "#{bin}/terraform-provider-docs-local --version"
  end
end
