# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformProviderDocsLocal < Formula
  desc "A tool for managing and browsing local copies of Terraform provider documentation"
  homepage "https://github.com/jreslock/terraform-provider-docs-local"
  version "0.0.20"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jreslock/terraform-provider-docs-local/releases/download/v0.0.20/terraform-provider-docs-local_darwin_x86_64.tar.gz"
      sha256 "40d19ca13665050458af7bc2949747b730bbd3039b08c02c08491ada9e148e6b"

      def install
        bin.install "terraform-provider-docs-local"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jreslock/terraform-provider-docs-local/releases/download/v0.0.20/terraform-provider-docs-local_darwin_arm64.tar.gz"
      sha256 "5f7aac0d8ef567cf99f617ac0253f92cb493a5b2861f255bb386a506b4ca53ad"

      def install
        bin.install "terraform-provider-docs-local"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jreslock/terraform-provider-docs-local/releases/download/v0.0.20/terraform-provider-docs-local_linux_x86_64.tar.gz"
        sha256 "6b4981d52e8064271503b5fab66bec8764215536f1e73762c7a55e8661f75fd0"

        def install
          bin.install "terraform-provider-docs-local"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jreslock/terraform-provider-docs-local/releases/download/v0.0.20/terraform-provider-docs-local_linux_arm64.tar.gz"
        sha256 "fc0d7ff37f91ae6bcd6a0ebc8e3430653e0bd1b394331f965ba881f0bdbbefe8"

        def install
          bin.install "terraform-provider-docs-local"
        end
      end
    end
  end

  test do
    system "#{bin}/terraform-provider-docs-local --version"
  end
end
